// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

//Import imports.dart
import 'package:flutter_proyecto_segunda_evaluacion/imports.dart';
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CTHFzbGucSysjLmYomkevb48ntrKB8g',
    appId: '1:20725459804:web:df65d437b0b025c3beaf99',
    messagingSenderId: '20725459804',
    projectId: 'flutterproyectosegundaev',
    authDomain: 'flutterproyectosegundaev.firebaseapp.com',
    storageBucket: 'flutterproyectosegundaev.appspot.com',
    measurementId: 'G-YCGFW0VXHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmsFkLYKBCNpV2lYiSOcEKYtAp6ZqkbcQ',
    appId: '1:20725459804:android:bbc341b431d5bcedbeaf99',
    messagingSenderId: '20725459804',
    projectId: 'flutterproyectosegundaev',
    storageBucket: 'flutterproyectosegundaev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_90BB8j2J0oAVnOVsQPU3WE7EfKUTG1Y',
    appId: '1:20725459804:ios:e3a3250dede65444beaf99',
    messagingSenderId: '20725459804',
    projectId: 'flutterproyectosegundaev',
    storageBucket: 'flutterproyectosegundaev.appspot.com',
    iosClientId: '20725459804-kugnca4ppe1bgb16ahfu0hkvctq9pbm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProyectoSegundaEvaluacion',
  );
}
